#!/usr/bin/env python3
# Copyright 2026 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Signature-drift: classify changes and prepare AI agent input.

Reads signature_changes.json produced by check_upstream_signatures.py and:
  - non_breaking_addition: info note in PR body only (no code edits)
  - param_rename:          info note in PR body only — no AI needed when kind,
                           required, and annotation all match
  - param_removal, others: routed to remaining_for_ai.json for the AI agent

Makes ZERO edits to any source file. All AI-bound changes are delegated to
the AI agent via generate_signature_drift_prompt.py.

Writes:
  - remaining_for_ai.json       — changes queued for the AI agent
  - pr_body_signature_drift.md  — PR description

GHA outputs:
  has_changes  — true if any drift was classified (gates PR creation)
  has_ai_work  — true if there are changes queued for the AI agent

Exit codes:
  0 — completed (or nothing to do)
  1 — error
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CHANGES_FILE = REPO_ROOT / "signature_changes.json"
AI_QUEUE_FILE = REPO_ROOT / "remaining_for_ai.json"
PR_BODY_FILE = REPO_ROOT / "pr_body_signature_drift.md"


# ---------------------------------------------------------------------------
# Info helpers
# ---------------------------------------------------------------------------


def fix_non_breaking_info(change: dict) -> str:
    """non_breaking_addition: no code change, just describe in PR body."""
    added = change.get("added", [])
    return (
        f"- `{change['key']}` (`{change.get('method', 'function')}`): "
        f"new optional parameter(s) `{'`, `'.join(added)}` — non-breaking, no action needed."
    )


def fix_rename_info(change: dict) -> str:
    """param_rename: mechanical rename confirmed by annotation match; note in PR body."""
    old_name = change.get("old_name", "?")
    new_name = change.get("new_name", "?")
    return (
        f"- `{change['key']}` (`{change.get('method', 'function')}`): "
        f"parameter renamed `{old_name}` → `{new_name}` "
        f"— update keyword-argument call sites."
    )


# ---------------------------------------------------------------------------
# PR body generation
# ---------------------------------------------------------------------------


def build_pr_body(
    non_breaking_notes: list[str],
    rename_notes: list[str],
    ai_queue: list[dict],
) -> str:
    sections = [
        "## Upstream Sync — Signature Drift\n",
        "_Auto-generated by the weekly upstream-sync bot._\n",
    ]

    if non_breaking_notes:
        sections.append("### Non-breaking additions (no code change required)\n")
        sections.extend(f"{n}\n" for n in non_breaking_notes)

    if rename_notes:
        sections.append("\n### Parameter renames (update keyword-argument call sites)\n")
        sections.append(
            "These renames were confirmed mechanically (same kind, required, and annotation). "
            "No AI agent was invoked — apply the renames at the listed call sites:\n"
        )
        sections.extend(f"{n}\n" for n in rename_notes)

    if ai_queue:
        sections.append("\n### Changes requiring AI agent review\n")
        sections.append(
            "The following changes were **not** auto-fixed. The AI agent will handle them in the same PR:\n"
        )
        for c in ai_queue:
            sections.append(
                f"- `{c['key']}` (`{c.get('method', 'function')}`): `{c['classification']}` — {c.get('type', '')}\n"
            )

    sections.append(
        "\n---\n"
        "**Checklist before merging:**\n"
        "- [ ] Apply any listed parameter renames to keyword-argument call sites\n"
        "- [ ] Run `pytest -s -x tests/special_sanity` locally\n"
        "- [ ] Verify any TODO comments above are resolved or intentionally deferred\n"
        "- [ ] Confirm AI agent changes are reviewed for correctness\n"
    )

    return "".join(sections)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    if not CHANGES_FILE.exists():
        print("No signature_changes.json found — nothing to apply.")
        return 0

    with open(CHANGES_FILE) as f:
        data = json.load(f)

    if not data.get("has_changes"):
        print("No changes to apply.")
        return 0

    all_changes = data.get("changes", [])

    non_breaking_notes: list[str] = []
    rename_notes: list[str] = []
    ai_queue: list[dict] = []

    for change in all_changes:
        cls = change.get("classification")
        if cls == "non_breaking_addition":
            non_breaking_notes.append(fix_non_breaking_info(change))
        elif cls == "param_rename":
            # Mechanical rename confirmed by annotation match — no AI needed
            rename_notes.append(fix_rename_info(change))
        else:
            # param_removal, others → AI agent
            ai_queue.append(change)

    # Write remaining_for_ai.json
    AI_QUEUE_FILE.write_text(json.dumps({"changes": ai_queue}, indent=2) + "\n")

    # Write PR body
    pr_body = build_pr_body(non_breaking_notes, rename_notes, ai_queue)
    PR_BODY_FILE.write_text(pr_body)

    # Summarize
    print("\nClassification summary:")
    print(f"  Non-breaking additions: {len(non_breaking_notes)}")
    print(f"  Renames (no AI):        {len(rename_notes)}")
    print(f"  Queued for AI agent:    {len(ai_queue)}")

    # Set GHA output
    import os

    has_changes = bool(non_breaking_notes or rename_notes or ai_queue)
    has_ai_work = bool(ai_queue)
    if gha_output := os.environ.get("GITHUB_OUTPUT"):
        with open(gha_output, "a") as f:
            f.write(f"has_changes={'true' if has_changes else 'false'}\n")
            f.write(f"has_ai_work={'true' if has_ai_work else 'false'}\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
