#!/usr/bin/env python3
# Copyright 2026 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Signature-drift: classify changes and prepare Cursor input.

Reads signature_changes.json produced by check_upstream_signatures.py and:
  - non_breaking_addition: collects info notes for the PR body (no code edits)
  - param_rename, param_removal, needs_ai_review: routed to remaining_for_cursor.json

Makes ZERO edits to any source file. All non-trivial changes are delegated to
Cursor via generate_signature_drift_prompt.py.

Writes:
  - remaining_for_cursor.json   — changes queued for the Cursor agent
  - pr_body_signature_drift.md  — PR description (non_breaking_addition notes only)

GHA outputs:
  has_pr_content   — true if there are non_breaking_addition notes to include
  has_cursor_work  — true if there are changes queued for Cursor

Exit codes:
  0 — completed (or nothing to do)
  1 — error
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CHANGES_FILE = REPO_ROOT / "signature_changes.json"
CURSOR_FILE = REPO_ROOT / "remaining_for_cursor.json"
PR_BODY_FILE = REPO_ROOT / "pr_body_signature_drift.md"


# ---------------------------------------------------------------------------
# Info helpers
# ---------------------------------------------------------------------------


def fix_non_breaking_info(change: dict) -> str:
    """non_breaking_addition: no code change, just describe in PR body."""
    added = change.get("added", [])
    return (
        f"- `{change['key']}` (`{change.get('method', 'function')}`): "
        f"new optional parameter(s) `{'`, `'.join(added)}` — non-breaking, no action needed."
    )


# ---------------------------------------------------------------------------
# PR body generation
# ---------------------------------------------------------------------------


def build_pr_body(
    non_breaking_notes: list[str],
    cursor_queue: list[dict],
) -> str:
    sections = [
        "## Upstream Sync — Signature Drift\n",
        "_Auto-generated by the daily upstream-sync bot._\n",
    ]

    if non_breaking_notes:
        sections.append("### Non-breaking additions (no code change required)\n")
        sections.extend(f"{n}\n" for n in non_breaking_notes)

    if cursor_queue:
        sections.append("\n### Changes requiring Cursor review\n")
        sections.append(
            "The following changes were **not** auto-fixed. "
            "Cursor will handle them in the same PR:\n"
        )
        for c in cursor_queue:
            sections.append(
                f"- `{c['key']}` (`{c.get('method', 'function')}`): "
                f"`{c['classification']}` — {c.get('type', '')}\n"
            )

    sections.append(
        "\n---\n"
        "**Checklist before merging:**\n"
        "- [ ] Run `pytest -s -x tests/special_sanity` locally\n"
        "- [ ] Verify any TODO comments above are resolved or intentionally deferred\n"
        "- [ ] Confirm Cursor changes are reviewed for correctness\n"
    )

    return "".join(sections)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    if not CHANGES_FILE.exists():
        print("No signature_changes.json found — nothing to apply.")
        return 0

    with open(CHANGES_FILE) as f:
        data = json.load(f)

    if not data.get("has_changes"):
        print("No changes to apply.")
        return 0

    all_changes = data.get("changes", [])

    non_breaking_notes: list[str] = []
    cursor_queue: list[dict] = []

    for change in all_changes:
        cls = change.get("classification")
        if cls == "non_breaking_addition":
            non_breaking_notes.append(fix_non_breaking_info(change))
        else:
            # param_rename, param_removal, needs_ai_review → all go to Cursor
            cursor_queue.append(change)

    # Write remaining_for_cursor.json
    CURSOR_FILE.write_text(json.dumps({"changes": cursor_queue}, indent=2) + "\n")

    # Write PR body
    pr_body = build_pr_body(non_breaking_notes, cursor_queue)
    PR_BODY_FILE.write_text(pr_body)

    # Summarize
    print("\nClassification summary:")
    print(f"  Non-breaking additions (info-only): {len(non_breaking_notes)}")
    print(f"  Queued for Cursor:                  {len(cursor_queue)}")

    # Set GHA output
    import os

    has_pr_content = bool(non_breaking_notes)
    has_cursor_work = bool(cursor_queue)
    if gha_output := os.environ.get("GITHUB_OUTPUT"):
        with open(gha_output, "a") as f:
            f.write(f"has_pr_content={'true' if has_pr_content else 'false'}\n")
            f.write(f"has_cursor_work={'true' if has_cursor_work else 'false'}\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
