#!/usr/bin/env bash
# SD3.5-Medium LoRA OCR recipe (V1 trainer: separate_async mode).
#
# This is the separate-async counterpart of run_sd35_medium_ocr_lora_v1.sh. It
# uses `verl_omni.trainer.main_diffusion_v1` with
# `trainer.v1.trainer_mode=separate_async`, which selects
# `PolicyGradientDiffusionTrainerV1SeparateAsync`. A standalone rollout manager
# serves generation traffic on dedicated GPUs while the colocated actor/rollout
# replicas sleep during training and may join generation when switched to
# rollout mode. Aborted diffusion samples are retried as whole samples by
# `DiffusionWholeSampleRetryLLMServerClient`.
#
# GPU layout (separate async needs dedicated rollout GPUs):
#   - NUM_GPUS_ACTOR:        colocated actor + colocated rollout GPUs (trainer.n_gpus_per_node)
#   - NUM_GPUS_STANDALONE:   standalone rollout GPUs (actor_rollout_ref.rollout.n_gpus_per_node)
#   - NUM_GPUS_REWARD:       reward model GPUs (separate resource pool)
#   Total visible GPUs must be >= NUM_GPUS_ACTOR + NUM_GPUS_STANDALONE + NUM_GPUS_REWARD.
#
# Requirements:
#   - actor_rollout_ref.rollout.nnodes > 0  (standalone rollout on dedicated GPUs)
#   - actor_rollout_ref.rollout.checkpoint_engine.backend != naive
#     (nccl/nixl/mooncake/...). CKPT_BACKEND below selects the backend; nccl is
#     the default. Make sure the corresponding checkpoint engine is importable.
#   - data.train_batch_size == parameter_sync_step * actor.ppo_mini_batch_size.
#
# Reference (sync v1 script):
# verl-omni/examples/flowgrpo_trainer/sd35/run_sd35_medium_ocr_lora_v1.sh
set -x

# Set OCR_WORKSPACE or WORKSPACE to any writable directory; defaults to $HOME.
WORKSPACE=${OCR_WORKSPACE:-${WORKSPACE:-$HOME}}

ocr_train_path=$WORKSPACE/data/ocr/sd3/train.parquet
ocr_test_path=$WORKSPACE/data/ocr/sd3/test.parquet

model_name=stabilityai/stable-diffusion-3.5-medium
reward_model_name=Qwen/Qwen2.5-VL-3B-Instruct
reward_function_path=verl_omni/utils/reward_score/genrm_ocr.py
custom_chat_template='{% for message in messages %}{% if message['\''role'\''] == '\''user'\'' %}{{ message['\''content'\''] }}{% endif %}{% endfor %}'

# --- GPU / parallelism layout (override via env) ---
NUM_GPUS_ACTOR=${NUM_GPUS_ACTOR:-2}          # colocated actor + rollout
NUM_GPUS_STANDALONE=${NUM_GPUS_STANDALONE:-2} # dedicated standalone rollout
NUM_GPUS_REWARD=${NUM_GPUS_REWARD:-1}
ROLLOUT_TP=${ROLLOUT_TP:-1}
REWARD_TP=${REWARD_TP:-1}
IMAGE_RESOLUTION=${IMAGE_RESOLUTION:-384}
TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS:-100}
ATTN_BACKEND=${ATTN_BACKEND:-native}
ROLLOUT_ATTN_BACKEND=${ROLLOUT_ATTN_BACKEND:-TORCH_SDPA}
MAX_NUM_SEQS=${MAX_NUM_SEQS:-256}

# Separate-async specific knobs.
CKPT_BACKEND=${CKPT_BACKEND:-nccl}                 # non-naive checkpoint backend
# Fully on-policy: no warmup backlog, sync weights every step, drop any
# trajectory not generated by the current model version. This makes
# separate_async behave synchronously (rollout and training no longer
# overlap) but guarantees only same-version rollouts are trained on.
NUM_WARMUP_BATCHES=${NUM_WARMUP_BATCHES:-0}
PARAMETER_SYNC_STEP=${PARAMETER_SYNC_STEP:-1}
MAX_OFF_POLICY_THRESHOLD=${MAX_OFF_POLICY_THRESHOLD:-1}
MAX_OFF_POLICY_STRATEGY=${MAX_OFF_POLICY_STRATEGY:-drop}
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-8}
PPO_MINI_BATCH_SIZE=$((TRAIN_BATCH_SIZE / PARAMETER_SYNC_STEP))
# Pause the standalone rollout during actor training (abort + remove from
# balancer on on_sample_end, resume after weight sync on on_step_end). With
# the on-policy knobs above this makes separate_async algorithmically
# identical to sync mode — just using dedicated rollout GPUs instead of
# colocated replicas. Set to 0 to allow async generation overlap.
SYNC_COMPATIBLE=${SYNC_COMPATIBLE:-1}

if [ "${FA3:-0}" = "1" ]; then
    ATTN_BACKEND="_flash_3_varlen_hub"
    ROLLOUT_ATTN_BACKEND=FLASH_ATTN_3_HUB
fi

ENGINE=vllm_omni
REWARD_ENGINE=vllm

# Pre-flight: verify the requested checkpoint backend is importable. The verl
# package silently swallows ImportError when registering nccl/nixl/mooncake, so
# we surface the real missing-dependency error here instead of failing later
# with "Checkpoint engine <backend> not registered".
python3 - <<PY
import importlib
import sys

backend = "$CKPT_BACKEND"
module_map = {
    "nccl": "verl.checkpoint_engine.nccl_checkpoint_engine",
    "nixl": "verl.checkpoint_engine.nixl_checkpoint_engine",
    "mooncake": "verl.checkpoint_engine.mooncake_checkpoint_engine",
    "hccl": "verl.checkpoint_engine.hccl_checkpoint_engine",
}
mod = module_map.get(backend)
if mod is None:
    sys.exit(0)  # unknown/custom backend; skip pre-flight
try:
    importlib.import_module(mod)
except Exception as e:
    print(f"Checkpoint backend '{backend}' could not be imported: {e}", file=sys.stderr)
    print(f"Install the required dependency. For 'nccl' that is typically:", file=sys.stderr)
    print(f"  pip install cupy-cuda12x   # match your CUDA major version (11x/12x/13x)", file=sys.stderr)
    print(f"  pip install pyzmq", file=sys.stderr)
    sys.exit(1)
PY

python3 -m verl_omni.trainer.main_diffusion_v1 \
    data.train_files=$ocr_train_path \
    data.val_files=$ocr_test_path \
    data.train_batch_size=$TRAIN_BATCH_SIZE \
    data.val_max_samples=32 \
    data.max_prompt_length=512 \
    data.truncation=error \
    data.seed=42 \
    actor_rollout_ref.model.algorithm=flow_grpo \
    actor_rollout_ref.actor.diffusion_loss.clip_ratio=1e-5 \
    actor_rollout_ref.model.path=$model_name \
    actor_rollout_ref.model.custom_chat_template="\"$custom_chat_template\"" \
    'actor_rollout_ref.model.extra_tokenizers={clip: {path: tokenizer, max_length: 77}, t5: {path: tokenizer_3, max_length: 256}}' \
    actor_rollout_ref.model.attn_backend=$ATTN_BACKEND \
    actor_rollout_ref.rollout.rollout_attn_backend=$ROLLOUT_ATTN_BACKEND \
    actor_rollout_ref.model.lora_rank=32 \
    actor_rollout_ref.model.lora_alpha=64 \
    actor_rollout_ref.model.target_modules="['to_q','to_k','to_v','to_out.0','add_q_proj','add_k_proj','add_v_proj','to_add_out']" \
    actor_rollout_ref.actor.optim.lr=1e-4 \
    actor_rollout_ref.actor.optim.weight_decay=0.0001 \
    actor_rollout_ref.actor.ppo_mini_batch_size=$PPO_MINI_BATCH_SIZE \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0.0 \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.actor.fsdp_config.model_dtype=bfloat16 \
    actor_rollout_ref.actor.strategy=fsdp2 \
    actor_rollout_ref.actor.fsdp_config.ulysses_sequence_parallel_size=1 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$ROLLOUT_TP \
    actor_rollout_ref.rollout.name=$ENGINE \
    actor_rollout_ref.rollout.mode=async \
    actor_rollout_ref.rollout.calculate_log_probs=True \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.seed=42 \
    actor_rollout_ref.rollout.nnodes=1 \
    actor_rollout_ref.rollout.n_gpus_per_node=$NUM_GPUS_STANDALONE \
    actor_rollout_ref.rollout.checkpoint_engine.backend=$CKPT_BACKEND \
    actor_rollout_ref.rollout.agent.num_workers=$((NUM_GPUS_ACTOR / ROLLOUT_TP)) \
    actor_rollout_ref.rollout.load_format=safetensors \
    actor_rollout_ref.rollout.pipeline.height=$IMAGE_RESOLUTION \
    actor_rollout_ref.rollout.pipeline.width=$IMAGE_RESOLUTION \
    actor_rollout_ref.rollout.pipeline.num_inference_steps=10 \
    actor_rollout_ref.rollout.pipeline.guidance_scale=1.0 \
    actor_rollout_ref.rollout.pipeline.max_sequence_length=256 \
    actor_rollout_ref.rollout.max_prompt_embed_length=333 \
    actor_rollout_ref.rollout.algo.noise_level=0.8 \
    actor_rollout_ref.rollout.algo.sde_type="cps" \
    actor_rollout_ref.rollout.algo.sde_window_size=3 \
    actor_rollout_ref.rollout.algo.sde_window_range="[0,5]" \
    +actor_rollout_ref.rollout.engine_kwargs.vllm_omni.max_num_seqs=$MAX_NUM_SEQS \
    actor_rollout_ref.rollout.val_kwargs.pipeline.num_inference_steps=28 \
    actor_rollout_ref.rollout.val_kwargs.algo.noise_level=0.0 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=8 \
    reward.num_workers=$((NUM_GPUS_REWARD / REWARD_TP)) \
    reward.reward_model.enable=True \
    reward.reward_model.model_path=$reward_model_name \
    reward.reward_model.rollout.name=$REWARD_ENGINE \
    reward.reward_model.enable_resource_pool=True \
    reward.reward_model.nnodes=1 \
    reward.reward_model.n_gpus_per_node=$NUM_GPUS_REWARD \
    reward.reward_model.rollout.gpu_memory_utilization=0.9 \
    reward.reward_model.rollout.free_cache_engine=False \
    reward.reward_model.rollout.tensor_model_parallel_size=$REWARD_TP \
    reward.reward_model.rollout.enforce_eager=False \
    reward.custom_reward_function.path=$reward_function_path \
    reward.custom_reward_function.name=compute_score_ocr \
    trainer.logger='["console", "wandb"]' \
    trainer.project_name=flow_grpo \
    trainer.experiment_name=sd35_medium_ocr_lora_v1_separate_async \
    trainer.log_val_generations=8 \
    trainer.val_before_train=False \
    trainer.n_gpus_per_node=$NUM_GPUS_ACTOR \
    trainer.nnodes=1 \
    trainer.save_freq=100 \
    trainer.test_freq=20 \
    trainer.total_epochs=15 \
    trainer.total_training_steps=$TOTAL_TRAINING_STEPS \
    trainer.use_v1=true \
    trainer.v1.trainer_mode=separate_async \
    trainer.v1.separate_async.num_warmup_batches=$NUM_WARMUP_BATCHES \
    trainer.v1.separate_async.parameter_sync_step=$PARAMETER_SYNC_STEP \
    trainer.v1.separate_async.sync_compatible=$SYNC_COMPATIBLE \
    trainer.v1.sampler.max_off_policy_threshold=$MAX_OFF_POLICY_THRESHOLD \
    trainer.v1.sampler.max_off_policy_strategy=$MAX_OFF_POLICY_STRATEGY "$@"
