#!/usr/bin/env bash
# 4-GPU local gate for pruned Qwen3-Omni Megatron + standalone vLLM-Omni.
# Default mode validates that standalone rollout really starts and generates;
# set VERL_OMNI_SKIP_WEIGHT_UPDATE=0 to include the trainer->rollout update.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ASYNC_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)/.."

export CONDA_ENV=${CONDA_ENV:-/nfs/ml-training-ssd/users/liuwei/verl_mega_async}
export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1,2,3}
export NUM_GPUS=${NUM_GPUS:-4}
export TRAIN_GPUS=${TRAIN_GPUS:-2}
export ROLLOUT_GPUS=${ROLLOUT_GPUS:-2}
export ROLLOUT_TP=${ROLLOUT_TP:-2}

export RUN_ID=${RUN_ID:-local4_vllm_gate_$(date +%Y%m%d_%H%M%S)}

export VERL_OMNI_FORCE_STANDALONE_ROLLOUT=${VERL_OMNI_FORCE_STANDALONE_ROLLOUT:-1}
export VERL_OMNI_RESOURCE_SPLIT_IMPL=${VERL_OMNI_RESOURCE_SPLIT_IMPL:-standalone_rollout}
export VERL_OMNI_TRAIN_GPUS_PER_NODE=${VERL_OMNI_TRAIN_GPUS_PER_NODE:-${TRAIN_GPUS}}
export VERL_OMNI_ROLLOUT_GPUS_PER_NODE=${VERL_OMNI_ROLLOUT_GPUS_PER_NODE:-${ROLLOUT_GPUS}}
export VERL_OMNI_ROLLOUT_NNODES=${VERL_OMNI_ROLLOUT_NNODES:-1}

export VERL_OMNI_SKIP_WEIGHT_UPDATE=${VERL_OMNI_SKIP_WEIGHT_UPDATE:-1}
export VERL_OMNI_SKIP_INITIAL_ROLLOUT_RESUME=${VERL_OMNI_SKIP_INITIAL_ROLLOUT_RESUME:-1}
export VERL_OMNI_SKIP_INITIAL_ROLLOUT_SLEEP=${VERL_OMNI_SKIP_INITIAL_ROLLOUT_SLEEP:-1}
export VERL_OMNI_WAKE_TAGS=${VERL_OMNI_WAKE_TAGS:-kv_cache,weights}
export VERL_OMNI_SLEEP_LEVEL=${VERL_OMNI_SLEEP_LEVEL:-1}

export VERL_OMNI_VLLM_PORT_SEED=${VERL_OMNI_VLLM_PORT_SEED:-${RUN_ID}}
export VERL_OMNI_VLLM_PORT_POOL_START=${VERL_OMNI_VLLM_PORT_POOL_START:-61000}
export VERL_OMNI_VLLM_PORT_POOL_END=${VERL_OMNI_VLLM_PORT_POOL_END:-65000}
export VERL_OMNI_VLLM_PORT_STRIDE=${VERL_OMNI_VLLM_PORT_STRIDE:-128}
export VERL_OMNI_VLLM_STAGE_CORE_PORT_OFFSET=${VERL_OMNI_VLLM_STAGE_CORE_PORT_OFFSET:-64}
export VERL_OMNI_VLLM_STAGE_CORE_PORT_GUARD=${VERL_OMNI_VLLM_STAGE_CORE_PORT_GUARD:-32}
export VERL_OMNI_VLLM_STAGE_CORE_PORT_SPREAD=${VERL_OMNI_VLLM_STAGE_CORE_PORT_SPREAD:-16}
export VERL_OMNI_VLLM_STAGE_CORE_PORT_MIN_TAIL=${VERL_OMNI_VLLM_STAGE_CORE_PORT_MIN_TAIL:-8}
export VERL_OMNI_VLLM_PORT_ACTOR_SLOTS=${VERL_OMNI_VLLM_PORT_ACTOR_SLOTS:-4}

export PYTHONPATH="${ASYNC_ROOT}/megatron-bridge/src:${PYTHONPATH:-}"

exec "${SCRIPT_DIR}/run_gspo_qwen3_omni_megatron_pruned_fully_async_smoke.sh" "$@"
