# Copyright 2026 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Custom vllm-omni pipeline for BAGEL RL rollouts with verl-omni.

Extends :class:`BagelPipeline` to:
* Replace the scheduler with an SDE scheduler for stochastic denoising
  with log-probability recording.
* Always enable trajectory recording.
* Read SDE kwargs from ``sampling_params.extra_args``.
* Return RL artifacts in ``DiffusionOutput.custom_output``.
"""

from __future__ import annotations

import hashlib
import logging
import random
from dataclasses import dataclass
from typing import Any, Optional

import numpy as np
import torch
from vllm_omni.diffusion.data import DiffusionOutput, OmniDiffusionConfig
from vllm_omni.diffusion.models.bagel.pipeline_bagel import BagelPipeline
from vllm_omni.diffusion.request import OmniDiffusionRequest

from verl_omni.pipelines.model_base import VllmOmniPipelineBase
from verl_omni.pipelines.schedulers import FlowMatchSDEDiscreteScheduler

logger = logging.getLogger(__name__)


# CFG defaults aligned with the original flow_grpo BAGEL training script
# (flow_grpo/scripts/train_bagel.py: inference_hyper) so that rollout (the
# behavior policy) and training-time log-prob recomputation use exactly the
# same CFG.  Any mismatch here biases the policy gradient because the
# trajectory was generated by a CFG-amplified velocity, while training would
# otherwise score it under a different (or non-)CFG velocity.
#
# Original flow_grpo Bagel uses:
#   cfg_text_scale = config.sample.guidance_scale  (= 4.0)
#   cfg_img_scale  = 1.0                            (disables img branch)
#   cfg_interval   = [0, 1.0]                       (always-on)
#   cfg_renorm_type = "global"
#   cfg_renorm_min  = 0.0
#
# NB: vllm-omni's BagelPipeline defaults are different (cfg_img_scale=1.5,
# cfg_interval=(0.4, 1.0)).  We deliberately override them here.
BAGEL_FLOWGRPO_CFG_DEFAULTS: dict[str, Any] = {
    "cfg_text_scale": 4.0,
    "cfg_img_scale": 1.0,
    "cfg_interval": (0.0, 1.0),
    "cfg_renorm_type": "global",
    "cfg_renorm_min": 0.0,
}


_CHAT_MARKERS = (
    "<|vision_start|>",
    "<|vision_end|>",
    "<|image_pad|>",
    "<|video_pad|>",
)


def _to_token_list(token_ids: Any) -> list[int] | None:
    if token_ids is None:
        return None
    if isinstance(token_ids, torch.Tensor):
        token_ids = token_ids.detach().cpu().tolist()
    if token_ids and isinstance(token_ids[0], list):
        token_ids = token_ids[0]
    return [int(token_id) for token_id in token_ids]


def _extract_prompt_text(decoded: str) -> str:
    if "<|im_start|>" in decoded:
        user_chunks = []
        for segment in decoded.split("<|im_start|>"):
            if not segment.startswith("user"):
                continue
            content = segment[len("user") :].lstrip("\n")
            content = content.split("<|im_end|>", 1)[0]
            user_chunks.append(content)
        if user_chunks:
            decoded = user_chunks[-1]

    for marker in _CHAT_MARKERS:
        decoded = decoded.replace(marker, "")
    return decoded.replace("<|im_start|>", "").replace("<|im_end|>", "").strip()


def _to_cpu_tensor(v):
    """Convert to a single CPU tensor, stacking a list of tensors if needed."""
    if isinstance(v, torch.Tensor):
        return v.detach().cpu()
    if isinstance(v, list):
        tensors = [x.detach().cpu() if isinstance(x, torch.Tensor) else torch.tensor(x) for x in v]
        return torch.stack(tensors) if tensors else None
    return v


@dataclass
class _AdapterStepOutput:
    """Adapter output matching what bagel_transformer.generate_image expects."""

    prev_sample: torch.Tensor
    log_prob: torch.Tensor | None


class _BagelSchedulerAdapter:
    """Wraps the diffusers-based FlowMatchSDEDiscreteScheduler to match
    BAGEL's calling convention: ``step(v_t, sigma, x_t, dt, **kwargs)``.

    BAGEL's transformer calls ``scheduler.step(model_output, timesteps[i],
    sample, dts[i], **scheduler_kwargs)`` with 4 positional args, while the
    diffusers scheduler takes ``step(model_output, timestep, sample, **kwargs)``
    and computes dt internally.  This adapter bridges the gap.

    Stateful SDE-windowing
    ----------------------
    Beyond the calling-convention adapter, this class also implements the
    "SDE window" behavior from flow_grpo's original BAGEL rollout
    (flow_grpo/flow_grpo/bagel/modeling/bagel/bagel.py::generate_image):
    noise is injected only on a contiguous window of denoising steps
    ``[window_begin, window_begin + window_size)``, while steps outside the
    window are run deterministically (ODE, ``noise_level=0``).  Log-prob
    recording is also gated to the window, otherwise outside-window steps
    would produce ``-inf`` / ``NaN`` log-probs (``std_dev_t == 0``).

    Without this windowing, ``noise_level`` would be injected at every step
    (e.g. 15 steps with ``noise_level=1.2``), the recorded latents would be
    far off the deterministic ODE manifold, rewards would flatten, and the
    PPO policy gradient would degenerate.  See the bug analysis in the
    chat history for the failure mode.
    """

    def __init__(self, inner: FlowMatchSDEDiscreteScheduler):
        self._inner = inner
        # Per-rollout state, reset via ``begin_forward``.
        self._sde_window: Optional[tuple[int, int]] = None
        self._base_noise_level: float = 0.0
        self._base_return_logprobs: bool = True
        self._step_counter: int = 0

    def __getattr__(self, name):
        return getattr(self._inner, name)

    def begin_forward(
        self,
        sde_window: Optional[tuple[int, int]],
        noise_level: float,
        return_logprobs: bool,
    ) -> None:
        """Reset adapter state before each rollout ``forward`` call.

        Args:
            sde_window: ``(begin, end_exclusive)`` step range where SDE
                noise is injected and log-probs are recorded.  ``None``
                disables windowing (legacy behavior: noise at every step).
            noise_level: SDE noise level to apply inside the window.
            return_logprobs: whether log-probs are requested at all
                (overridden to ``False`` outside the window even when
                ``True`` here).
        """
        self._sde_window = sde_window
        self._base_noise_level = float(noise_level)
        self._base_return_logprobs = bool(return_logprobs)
        self._step_counter = 0

    def step(
        self,
        model_output: torch.Tensor,
        sigma: float | torch.Tensor,
        sample: torch.Tensor,
        dt: float | torch.Tensor,  # noqa: ARG002 — inner derives dt from timestep schedule
        **kwargs,
    ) -> _AdapterStepOutput:
        i = self._step_counter
        if self._sde_window is not None:
            begin, end = self._sde_window
            in_window = begin <= i < end
            # Inside window  -> use configured noise_level & record log_prob.
            # Outside window -> deterministic ODE; skip log_prob (otherwise
            # std_dev_t = 0 -> log(0) = -inf in sample_previous_step).
            cur_noise_level = self._base_noise_level if in_window else 0.0
            cur_return_logprobs = self._base_return_logprobs and in_window
            kwargs = {
                **kwargs,
                "noise_level": cur_noise_level,
                "return_logprobs": cur_return_logprobs,
            }
        # else: pass caller kwargs through unchanged (legacy behavior).

        out = self._inner.step(
            model_output=model_output,
            timestep=sigma,
            sample=sample,
            return_dict=False,
            **kwargs,
        )
        self._step_counter += 1
        # step() with return_dict=False returns
        # (prev_sample, log_prob, prev_sample_mean, std_dev_t)
        prev_sample, log_prob = out[0], out[1]
        # BAGEL packs latents as ``(num_tokens, channels)`` per request (no
        # explicit batch dim, since rollout handles one sample at a time).
        # The inner scheduler's ``mean(dim=tuple(range(1, ndim)))`` therefore
        # preserves the spatial-token dim, yielding ``(num_tokens,)`` instead
        # of a scalar.  At training time, latents *do* have a batch dim
        # (``(B, num_tokens, channels)``), so the same reduction yields
        # ``(B,)``.  Without the extra reduction here, ``old_log_probs`` ends
        # up with shape ``(B, num_steps, num_tokens)`` while training's
        # ``log_prob`` is ``(B,)`` — broadcasting then fails inside
        # ``compute_diffusion_loss_flow_grpo``.  Match the original flow_grpo
        # behavior (``log_prob.mean()`` in ``bagel.py::_sde_step_with_logprob``)
        # by fully reducing to a per-step scalar.
        if log_prob is not None:
            log_prob = log_prob.mean()
        return _AdapterStepOutput(prev_sample=prev_sample, log_prob=log_prob)


def _pick_sde_window(
    window_size: Optional[int],
    window_range: Optional[Any],
    seed: Optional[int],
    request_id: Optional[str],
) -> Optional[tuple[int, int]]:
    """Pick a contiguous SDE window ``[begin, begin + window_size)`` randomly
    inside ``window_range`` (inclusive).  Returns ``None`` when windowing is
    disabled (``window_size`` is ``None`` or 0).

    Reproducibility:
    * ``seed != None``        -> seed Python RNG with ``seed``.
    * ``request_id`` provided -> seed RNG with sha256(request_id) so
      concurrent requests inside one process still get different windows.
    * Both ``None``           -> use default RNG (non-deterministic).

    This mirrors flow_grpo's ``random.randint(window_range[0],
    window_range[1] - window_size)`` call but is seeded per-request rather
    than per-process so that different rollouts inside one replica explore
    different parts of the trajectory.
    """
    if window_size is None or int(window_size) <= 0:
        return None
    if window_range is None:
        return (0, int(window_size))

    low = int(window_range[0])
    high = int(window_range[1])
    high_inclusive = high - int(window_size)
    if high_inclusive < low:
        # Window doesn't fit; clamp to the lowest valid begin.
        return (low, low + int(window_size))

    if seed is not None:
        rng = random.Random(int(seed))
    elif request_id is not None:
        h = hashlib.sha256(str(request_id).encode()).digest()
        rng = random.Random(int.from_bytes(h[:8], "big"))
    else:
        rng = random.Random()
    begin = rng.randint(low, high_inclusive)
    return (begin, begin + int(window_size))


@VllmOmniPipelineBase.register("OmniBagelForConditionalGeneration", algorithm="flow_grpo")
class BagelPipelineWithLogProb(BagelPipeline):
    """BAGEL pipeline variant for RL rollouts with verl-omni."""

    def __init__(self, *, od_config: OmniDiffusionConfig, prefix: str = ""):
        super().__init__(od_config=od_config, prefix=prefix)
        inner = FlowMatchSDEDiscreteScheduler()
        self.scheduler = _BagelSchedulerAdapter(inner)
        logger.info("BagelPipelineWithLogProb: SDE scheduler enabled for RL rollouts")

    def _decode_token_prompt(self, token_ids: Any) -> str | None:
        token_list = _to_token_list(token_ids)
        if not token_list:
            return None
        decoded = self.tokenizer.decode(token_list, skip_special_tokens=False)
        return _extract_prompt_text(decoded)

    def _ensure_bagel_prompt_text(self, req: OmniDiffusionRequest) -> None:
        if not req.prompts or not isinstance(req.prompts[0], dict):
            return

        custom_prompt = req.prompts[0]
        if not custom_prompt.get("prompt"):
            prompt = self._decode_token_prompt(custom_prompt.get("prompt_token_ids"))
            if prompt is not None:
                custom_prompt["prompt"] = prompt

        extra_args = req.sampling_params.extra_args
        if "negative_prompt" not in extra_args:
            negative_prompt = self._decode_token_prompt(custom_prompt.get("negative_prompt_ids"))
            if negative_prompt is not None:
                extra_args["negative_prompt"] = negative_prompt

        prompt_extra_args = custom_prompt.get("extra_args")
        if isinstance(prompt_extra_args, dict):
            multi_modal_data = prompt_extra_args.get("multi_modal_data")
            if multi_modal_data is not None and "multi_modal_data" not in custom_prompt:
                custom_prompt["multi_modal_data"] = multi_modal_data

    def forward(self, req: OmniDiffusionRequest) -> DiffusionOutput:
        self._ensure_bagel_prompt_text(req)

        # Force trajectory recording on for RL
        req.sampling_params.return_trajectory_latents = True

        extra_args = req.sampling_params.extra_args

        # ----------------------------------------------------------------- #
        # Bug 2 fix (rollout side):                                          #
        # Force the BAGEL CFG kwargs that BagelPipeline.forward reads from   #
        # ``extra_args`` to flow_grpo's training defaults *unless* the       #
        # caller has explicitly set them.  This keeps the rollout (behavior  #
        # policy) byte-identical with the CFG that the training adapter     #
        # applies when recomputing log-probs, so the importance-sampling    #
        # ratio is not silently biased by a CFG mismatch.                    #
        # ----------------------------------------------------------------- #
        for k, v in BAGEL_FLOWGRPO_CFG_DEFAULTS.items():
            extra_args.setdefault(k, v)
        # OmegaConf delivers tuples as lists; BagelPipeline expects a tuple.
        if isinstance(extra_args.get("cfg_interval"), list):
            extra_args["cfg_interval"] = tuple(extra_args["cfg_interval"])

        # ----------------------------------------------------------------- #
        # Bug 1 fix: SDE windowing.                                          #
        # Pick a contiguous denoising-step window inside which we apply SDE  #
        # noise and record (latent, log_prob, sigma) triplets; the rest of   #
        # the trajectory runs deterministically (ODE).  This mirrors         #
        # generate_image() in flow_grpo's bagel.py and is what the training  #
        # loss expects when iterating ``range(num_recorded_steps)``.         #
        # ----------------------------------------------------------------- #
        logprobs = bool(extra_args.get("logprobs", True))
        noise_level = float(extra_args.get("noise_level", 0.0))
        sde_window_size = extra_args.get("sde_window_size", None)
        sde_window_range = extra_args.get("sde_window_range", None)
        if isinstance(sde_window_range, list):
            sde_window_range = tuple(sde_window_range)

        sde_window: Optional[tuple[int, int]] = None
        if sde_window_size and noise_level > 0.0:
            sde_window = _pick_sde_window(
                window_size=int(sde_window_size),
                window_range=sde_window_range,
                seed=req.sampling_params.seed,
                request_id=getattr(req, "request_id", None),
            )

        # Scheduler kwargs passed to every step.  ``_BagelSchedulerAdapter``
        # overrides ``noise_level`` and ``return_logprobs`` per-step based
        # on whether the step is inside ``sde_window``; we still pass these
        # defaults so the no-window legacy path works.
        self.scheduler_kwargs = {k: extra_args[k] for k in ("noise_level", "sde_type", "generator") if k in extra_args}
        self.scheduler_kwargs["return_logprobs"] = logprobs

        # Per-request scheduler setup: compute BAGEL's shifted sigmas so
        # the inner SDE scheduler's sigma schedule matches what
        # generate_image() computes internally.
        assert req.sampling_params.num_inference_steps is not None, "num_inference_steps must be set for RL rollouts"
        num_timesteps = req.sampling_params.num_inference_steps
        timestep_shift = 3.0  # must match BagelPipeline.forward() hardcoded value

        t = np.linspace(1, 0, num_timesteps)
        t_shifted = timestep_shift * t / (1 + (timestep_shift - 1) * t)
        sigmas = t_shifted[:-1].tolist()  # drop terminal 0; set_timesteps appends it

        inner = self.scheduler._inner
        inner.set_shift(1.0)  # identity — sigmas already shifted
        # Pass ``timesteps=sigmas`` explicitly so diffusers does NOT multiply
        # sigmas by ``num_train_timesteps`` (1000).  While ``set_begin_index(0)``
        # below bypasses ``index_for_timestep`` on the rollout path, keeping
        # this explicit prevents a latent bug if the sequential-step-index
        # behaviour is ever changed.
        inner.set_timesteps(sigmas=sigmas, timesteps=sigmas)
        inner.set_begin_index(0)

        # Reset the stateful adapter for this request (must happen *after*
        # ``set_timesteps`` so that the inner step_index is None again).
        self.scheduler.begin_forward(
            sde_window=sde_window,
            noise_level=noise_level,
            return_logprobs=logprobs,
        )

        output = super().forward(req)

        # ----------------------------------------------------------------- #
        # Slice the recorded trajectory to the SDE window so the training   #
        # adapter iterates only on steps where noise was actually injected. #
        # ``trajectory_log_probs`` is already window-length (None entries    #
        # are dropped in generate_image), but ``trajectory_latents`` and    #
        # ``trajectory_timesteps`` record *all* steps unconditionally.      #
        # ----------------------------------------------------------------- #
        traj_latents = output.trajectory_latents
        traj_timesteps = output.trajectory_timesteps
        traj_log_probs = output.trajectory_log_probs

        if sde_window is not None:
            begin, end = sde_window
            if traj_latents is not None:
                # shape: (num_steps + 1, ...); keep x at sigma_begin .. sigma_end
                traj_latents = traj_latents[begin : end + 1]
            if traj_timesteps is not None:
                # shape: (num_steps,); keep sigma_begin .. sigma_{end-1}
                traj_timesteps = traj_timesteps[begin:end]
            # traj_log_probs already has length (end - begin) thanks to
            # _BagelSchedulerAdapter gating; no slicing needed.

        custom = output.custom_output or {}
        if traj_latents is not None:
            custom["all_latents"] = _to_cpu_tensor(traj_latents)
        if traj_timesteps is not None:
            custom["all_timesteps"] = _to_cpu_tensor(traj_timesteps)
        if traj_log_probs is not None:
            custom["all_log_probs"] = _to_cpu_tensor(traj_log_probs)
        output.custom_output = custom

        return output
